<label for="brand" class="form-label">Brand</label>
<select id="brand" class="form-select" name="brand">
    <option selected value="">All brands</option>
    <option value="abarth">Abarth</option>
    <option value="acura">Acura</option>
    <option value="alfa-romeo">Alfa Romeo</option>
    <option value="alpina">Alpina</option>
    <option value="aston-martin">Aston Martin</option>
    <option value="audi">Audi</option>
    <option value="bentley">Bentley</option>
    <option value="bmw">BMW</option>
    <option value="bugatti">Bugatti</option>
    <option value="buick">Buick</option>
    <option value="cadillac">Cadillac</option>
    <option value="chevrolet">Chevrolet</option>
    <option value="chrysler">Chrysler</option>
    <option value="citroen">Citroën</option>
    <option value="cupra">Cupra</option>
    <option value="dacia">Dacia</option>
    <option value="dodge">Dodge</option>
    <option value="ferrari">Ferrari</option>
    <option value="fiat">Fiat</option>
    <option value="ford">Ford</option>
    <option value="genesis">Genesis</option>
    <option value="gmc">GMC</option>
    <option value="honda">Honda</option>
    <option value="hyundai">Hyundai</option>
    <option value="infiniti">Infiniti</option>
    <option value="jaguar">Jaguar</option>
    <option value="jeep">Jeep</option>
    <option value="kia">Kia</option>
    <option value="koenigsegg">Koenigsegg</option>
    <option value="lamborghini">Lamborghini</option>
    <option value="land-rover">Land Rover</option>
    <option value="lexus">Lexus</option>
    <option value="lincoln">Lincoln</option>
    <option value="lotus">Lotus</option>
    <option value="mazda">Mazda</option>
    <option value="maserati">Maserati</option>
    <option value="mclaren">McLaren</option>
    <option value="mercedes-benz">Mercedes-Benz</option>
    <option value="mini">Mini</option>
    <option value="mitsubishi">Mitsubishi</option>
    <option value="nissan">Nissan</option>
    <option value="pagani">Pagani</option>
    <option value="peugeot">Peugeot</option>
    <option value="porsche">Porsche</option>
    <option value="ram">RAM</option>
    <option value="renault">Renault</option>
    <option value="rolls-royce">Rolls-Royce</option>
    <option value="seat">SEAT</option>
    <option value="skoda">Skoda</option>
    <option value="subaru">Subaru</option>
    <option value="suzuki">Suzuki</option>
    <option value="tesla">Tesla</option>
    <option value="toyota">Toyota</option>
    <option value="volkswagen">Volkswagen</option>
    <option value="volvo">Volvo</option>
</select>

