name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up PHP
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, bcmath, pdo_mysql # Use pdo_mysql for Laravel

    # Step 2: Checkout code from repository
    - uses: actions/checkout@v4

    # Step 3: Copy .env file
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # Step 4: Set Environment Variables for Testing
    - name: Set Environment Variables for Testing
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_DATABASE=polovni-automobili" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env

    # Step 5: Install Dependencies
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # Step 6: Generate Laravel application key
    - name: Generate key
      run: php artisan key:generate

    # Step 7: Set proper permissions for storage and cache directories
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Step 8: Start MySQL service
    - name: Start MySQL Service
      run: sudo service mysql start

    # Step 9: Create Database
    - name: Create Database
      run: |
        mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS \`polovni-automobili\`;"

    # Step 10: Run Migrations
    - name: Run Migrations
      run: php artisan migrate --force --env=testing

    # Step 11: Run tests (Unit and Feature tests) via PHPUnit/Pest
    - name: Run Tests
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: polovni-automobili
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan test
